/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DigitalNewzealand.PCL;

namespace DigitalNewzealand.PCL.Models
{
    public class CollectionSearchRecords : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int numResultsRequested;
        private int resultCount;
        private string start;
        private ResultsCollection results;
        private Dictionary<string, object> facets;

        /// <summary>
        /// the value of the num_results parameter sent to the API method
        /// </summary>
        [JsonProperty("num_results_requested")]
        public int NumResultsRequested 
        { 
            get 
            {
                return this.numResultsRequested; 
            } 
            set 
            {
                this.numResultsRequested = value;
                onPropertyChanged("NumResultsRequested");
            }
        }

        /// <summary>
        /// the total number of results matching this search
        /// </summary>
        [JsonProperty("result_count")]
        public int ResultCount 
        { 
            get 
            {
                return this.resultCount; 
            } 
            set 
            {
                this.resultCount = value;
                onPropertyChanged("ResultCount");
            }
        }

        /// <summary>
        /// the value of the start parameter sent to the API method
        /// </summary>
        [JsonProperty("start")]
        public string Start 
        { 
            get 
            {
                return this.start; 
            } 
            set 
            {
                this.start = value;
                onPropertyChanged("Start");
            }
        }

        /// <summary>
        /// the search results data. The results element will contain 0 or more result elements
        /// </summary>
        [JsonProperty("results")]
        public ResultsCollection Results 
        { 
            get 
            {
                return this.results; 
            } 
            set 
            {
                this.results = value;
                onPropertyChanged("Results");
            }
        }

        /// <summary>
        /// the facet result data (if requested). The facets element will contain one facet-field element corresponding to each facet requested. Each facet-field element contains a sorted list of value elements that are made up of a name and num-results element. 
        /// </summary>
        [JsonProperty("facets")]
        public Dictionary<string, object> Facets 
        { 
            get 
            {
                return this.facets; 
            } 
            set 
            {
                this.facets = value;
                onPropertyChanged("Facets");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 