/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DigitalNewzealand.PCL;

namespace DigitalNewzealand.PCL.Models
{
    public class RecordsSet : SetsBase 
    {
        // These fields hold the values for the public properties.
        private string description;
        private string privacy;
        private List<string> tags;
        private List<Record> records;
        private string user;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("privacy")]
        public string Privacy 
        { 
            get 
            {
                return this.privacy; 
            } 
            set 
            {
                this.privacy = value;
                onPropertyChanged("Privacy");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("tags")]
        public List<string> Tags 
        { 
            get 
            {
                return this.tags; 
            } 
            set 
            {
                this.tags = value;
                onPropertyChanged("Tags");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("records")]
        public List<Record> Records 
        { 
            get 
            {
                return this.records; 
            } 
            set 
            {
                this.records = value;
                onPropertyChanged("Records");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("user")]
        public string User 
        { 
            get 
            {
                return this.user; 
            } 
            set 
            {
                this.user = value;
                onPropertyChanged("User");
            }
        }
    }
} 