/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DigitalNewzealand.PCL;

namespace DigitalNewzealand.PCL.Models
{
    public class Record : RecordBase 
    {
        // These fields hold the values for the public properties.
        private string title;
        private string description;
        private string largeThumbnailUrl;
        private string thumbnailUrl;
        private string displayContentPartner;
        private string displayCollection;
        private string landingUrl;
        private List<string> category;
        private DateTime? date;
        private string dnzType;
        private List<string> dcIdentifier;
        private string creator;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("large_thumbnail_url")]
        public string LargeThumbnailUrl 
        { 
            get 
            {
                return this.largeThumbnailUrl; 
            } 
            set 
            {
                this.largeThumbnailUrl = value;
                onPropertyChanged("LargeThumbnailUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl 
        { 
            get 
            {
                return this.thumbnailUrl; 
            } 
            set 
            {
                this.thumbnailUrl = value;
                onPropertyChanged("ThumbnailUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("display_content_partner")]
        public string DisplayContentPartner 
        { 
            get 
            {
                return this.displayContentPartner; 
            } 
            set 
            {
                this.displayContentPartner = value;
                onPropertyChanged("DisplayContentPartner");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("display_collection")]
        public string DisplayCollection 
        { 
            get 
            {
                return this.displayCollection; 
            } 
            set 
            {
                this.displayCollection = value;
                onPropertyChanged("DisplayCollection");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("landing_url")]
        public string LandingUrl 
        { 
            get 
            {
                return this.landingUrl; 
            } 
            set 
            {
                this.landingUrl = value;
                onPropertyChanged("LandingUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("category")]
        public List<string> Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("date")]
        public DateTime? Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dnz_type")]
        public string DnzType 
        { 
            get 
            {
                return this.dnzType; 
            } 
            set 
            {
                this.dnzType = value;
                onPropertyChanged("DnzType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dc_identifier")]
        public List<string> DcIdentifier 
        { 
            get 
            {
                return this.dcIdentifier; 
            } 
            set 
            {
                this.dcIdentifier = value;
                onPropertyChanged("DcIdentifier");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creator")]
        public string Creator 
        { 
            get 
            {
                return this.creator; 
            } 
            set 
            {
                this.creator = value;
                onPropertyChanged("Creator");
            }
        }
    }
} 