/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DigitalNewzealand.PCL;

namespace DigitalNewzealand.PCL.Models
{
    public class ResultsCollection : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private bool isCommercialUse;
        private string category;
        private string contentPartner;
        private DateTime? date;
        private string description;
        private string additionalDescription;
        private string landingUrl;
        private string id;
        private string sourceUrl;
        private DateTime syndicationDate;
        private string thumbnailUrl;
        private string title;
        private string geoCoOrds;
        private string largeThumbnailUrl;
        private string copyright;
        private string license;
        private string rightsUrl;
        private string displayDate;
        private bool peerReviewed;
        private int marsdenCode;
        private string author;
        private bool noLandingPage;
        private string objectUrl;
        private string publishedDate;
        private string publisher;
        private string dctype;
        private string libraryCollection;
        private string displayCollection;
        private string collectionParent;
        private string collectionRoot;

        /// <summary>
        /// this record is licensed for commercial use
        /// </summary>
        [JsonProperty("is_commercial_use ")]
        public bool IsCommercialUse 
        { 
            get 
            {
                return this.isCommercialUse; 
            } 
            set 
            {
                this.isCommercialUse = value;
                onPropertyChanged("IsCommercialUse");
            }
        }

        /// <summary>
        /// a string containing one or more category names separated by a comma (e.g. Images, Web pages)
        /// </summary>
        [JsonProperty("category")]
        public string Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// the institution holding the content to which the record refers
        /// </summary>
        [JsonProperty("content_partner")]
        public string ContentPartner 
        { 
            get 
            {
                return this.contentPartner; 
            } 
            set 
            {
                this.contentPartner = value;
                onPropertyChanged("ContentPartner");
            }
        }

        /// <summary>
        /// a date associated with the record (e.g. 1996-01-01T00:00:00.000Z). This field may be empty
        /// </summary>
        [JsonProperty("date")]
        public DateTime? Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// text describing the record
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// additional text describing the record
        /// </summary>
        [JsonProperty("additional_description")]
        public string AdditionalDescription 
        { 
            get 
            {
                return this.additionalDescription; 
            } 
            set 
            {
                this.additionalDescription = value;
                onPropertyChanged("AdditionalDescription");
            }
        }

        /// <summary>
        ///  the url for the content on the contentpartner's website. Please use the source_url when providing HTML links (see below)
        /// </summary>
        [JsonProperty("landing_url")]
        public string LandingUrl 
        { 
            get 
            {
                return this.landingUrl; 
            } 
            set 
            {
                this.landingUrl = value;
                onPropertyChanged("LandingUrl");
            }
        }

        /// <summary>
        /// the internal DigitalNZ identifier (used by the Get Metadata API)
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// the url that will redirect users to the landing_url. By using this link (as opposed to the display_url) we are able to count clickthroughs which is helpful for demonstrating the value of DigitalNZ
        /// </summary>
        [JsonProperty("source_url")]
        public string SourceUrl 
        { 
            get 
            {
                return this.sourceUrl; 
            } 
            set 
            {
                this.sourceUrl = value;
                onPropertyChanged("SourceUrl");
            }
        }

        /// <summary>
        /// the date the record was added to DigitalNZ
        /// </summary>
        [JsonProperty("syndication_date")]
        public DateTime SyndicationDate 
        { 
            get 
            {
                return this.syndicationDate; 
            } 
            set 
            {
                this.syndicationDate = value;
                onPropertyChanged("SyndicationDate");
            }
        }

        /// <summary>
        /// the url of for a thumbnail image of the content to which the record refers. This field may be empty.
        /// </summary>
        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl 
        { 
            get 
            {
                return this.thumbnailUrl; 
            } 
            set 
            {
                this.thumbnailUrl = value;
                onPropertyChanged("ThumbnailUrl");
            }
        }

        /// <summary>
        /// the title of the record
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// The latitude and longitude in the following format: namespace:lat,long; Multiple values are seperated by semi-colons, for example: namespace:lat,long;namespace:lat,long;namespace:lat,long; NOTE: namespace is optional.
        /// </summary>
        [JsonProperty("geo_co_ords")]
        public string GeoCoOrds 
        { 
            get 
            {
                return this.geoCoOrds; 
            } 
            set 
            {
                this.geoCoOrds = value;
                onPropertyChanged("GeoCoOrds");
            }
        }

        /// <summary>
        /// a larger thumbnail image with dimensions up to 800px (NB the API Terms do not extend rights to the use of these thumbnails)
        /// </summary>
        [JsonProperty("large_thumbnail_url")]
        public string LargeThumbnailUrl 
        { 
            get 
            {
                return this.largeThumbnailUrl; 
            } 
            set 
            {
                this.largeThumbnailUrl = value;
                onPropertyChanged("LargeThumbnailUrl");
            }
        }

        /// <summary>
        /// the copyright statement applying to the object. This field may be empty.
        /// </summary>
        [JsonProperty("copyright")]
        public string Copyright 
        { 
            get 
            {
                return this.copyright; 
            } 
            set 
            {
                this.copyright = value;
                onPropertyChanged("Copyright");
            }
        }

        /// <summary>
        /// the licence for the object. This field may be empty
        /// </summary>
        [JsonProperty("license")]
        public string License 
        { 
            get 
            {
                return this.license; 
            } 
            set 
            {
                this.license = value;
                onPropertyChanged("License");
            }
        }

        /// <summary>
        /// the url of the object licence. This field may be empty.
        /// </summary>
        [JsonProperty("rights_url")]
        public string RightsUrl 
        { 
            get 
            {
                return this.rightsUrl; 
            } 
            set 
            {
                this.rightsUrl = value;
                onPropertyChanged("RightsUrl");
            }
        }

        /// <summary>
        /// string with date information in multiple, often unstructured formats (e.g. Circa 2000)
        /// </summary>
        [JsonProperty("display_date")]
        public string DisplayDate 
        { 
            get 
            {
                return this.displayDate; 
            } 
            set 
            {
                this.displayDate = value;
                onPropertyChanged("DisplayDate");
            }
        }

        /// <summary>
        /// boolean, associated with research paper items. True indicates the research paper has been peer reviewed
        /// </summary>
        [JsonProperty("peer_reviewed")]
        public bool PeerReviewed 
        { 
            get 
            {
                return this.peerReviewed; 
            } 
            set 
            {
                this.peerReviewed = value;
                onPropertyChanged("PeerReviewed");
            }
        }

        /// <summary>
        /// a number indicating the field of research
        /// </summary>
        [JsonProperty("marsden_code")]
        public int MarsdenCode 
        { 
            get 
            {
                return this.marsdenCode; 
            } 
            set 
            {
                this.marsdenCode = value;
                onPropertyChanged("MarsdenCode");
            }
        }

        /// <summary>
        /// lists the author's names
        /// </summary>
        [JsonProperty("author")]
        public string Author 
        { 
            get 
            {
                return this.author; 
            } 
            set 
            {
                this.author = value;
                onPropertyChanged("Author");
            }
        }

        /// <summary>
        /// boolean value, if set to true it indicates the item doesn't have an external landing page, usually because it is a downloadable item such as a pdf or mpeg
        /// </summary>
        [JsonProperty("no_landing_page")]
        public bool NoLandingPage 
        { 
            get 
            {
                return this.noLandingPage; 
            } 
            set 
            {
                this.noLandingPage = value;
                onPropertyChanged("NoLandingPage");
            }
        }

        /// <summary>
        /// a url pointing to a downloadable object, i.e. an image, pdf or mpeg
        /// </summary>
        [JsonProperty("object_url")]
        public string ObjectUrl 
        { 
            get 
            {
                return this.objectUrl; 
            } 
            set 
            {
                this.objectUrl = value;
                onPropertyChanged("ObjectUrl");
            }
        }

        /// <summary>
        /// list of dates published 
        /// </summary>
        [JsonProperty("published_date")]
        public string PublishedDate 
        { 
            get 
            {
                return this.publishedDate; 
            } 
            set 
            {
                this.publishedDate = value;
                onPropertyChanged("PublishedDate");
            }
        }

        /// <summary>
        /// lists the publisher's names
        /// </summary>
        [JsonProperty("publisher")]
        public string Publisher 
        { 
            get 
            {
                return this.publisher; 
            } 
            set 
            {
                this.publisher = value;
                onPropertyChanged("Publisher");
            }
        }

        /// <summary>
        ///  Dublin Core categorisation indicating type
        /// </summary>
        [JsonProperty("dctype")]
        public string Dctype 
        { 
            get 
            {
                return this.dctype; 
            } 
            set 
            {
                this.dctype = value;
                onPropertyChanged("Dctype");
            }
        }

        /// <summary>
        /// the library collection the item belongs to
        /// </summary>
        [JsonProperty("library_collection")]
        public string LibraryCollection 
        { 
            get 
            {
                return this.libraryCollection; 
            } 
            set 
            {
                this.libraryCollection = value;
                onPropertyChanged("LibraryCollection");
            }
        }

        /// <summary>
        /// the display collection the item belongs to
        /// </summary>
        [JsonProperty("display_collection")]
        public string DisplayCollection 
        { 
            get 
            {
                return this.displayCollection; 
            } 
            set 
            {
                this.displayCollection = value;
                onPropertyChanged("DisplayCollection");
            }
        }

        /// <summary>
        /// the item's parent collection
        /// </summary>
        [JsonProperty("collection_parent")]
        public string CollectionParent 
        { 
            get 
            {
                return this.collectionParent; 
            } 
            set 
            {
                this.collectionParent = value;
                onPropertyChanged("CollectionParent");
            }
        }

        /// <summary>
        /// the top level collection
        /// </summary>
        [JsonProperty("collection_root")]
        public string CollectionRoot 
        { 
            get 
            {
                return this.collectionRoot; 
            } 
            set 
            {
                this.collectionRoot = value;
                onPropertyChanged("CollectionRoot");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 