/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using DigitalNewzealand.PCL;

namespace DigitalNewzealand.PCL.Models
{
    public class UserSets : SetsBase 
    {
        // These fields hold the values for the public properties.
        private List<RecordBase> records;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("records")]
        public List<RecordBase> Records 
        { 
            get 
            {
                return this.records; 
            } 
            set 
            {
                this.records = value;
                onPropertyChanged("Records");
            }
        }
    }
} 