/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;

namespace DigitalNewzealand.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "http://api.digitalnz.org";

        //Your API Key
        //TODO: Replace the ApiKey with an appropriate value
        public static string ApiKey = "TODO: Replace";

    }
}