/*
 * DigitalNewzealand.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2016
 */
using System;
using DigitalNewzealand.PCL.Controllers;

namespace DigitalNewzealand.PCL
{
    public partial class DigitalNewzealandClient
    {

        /// <summary>
        /// Singleton access to SearchRecord controller
        /// </summary>
        public SearchRecordController SearchRecord
        {
            get
            {
                return SearchRecordController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Metadata controller
        /// </summary>
        public MetadataController Metadata
        {
            get
            {
                return MetadataController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ContentPartners controller
        /// </summary>
        public ContentPartnersController ContentPartners
        {
            get
            {
                return ContentPartnersController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Sets controller
        /// </summary>
        public SetsController Sets
        {
            get
            {
                return SetsController.Instance;
            }
        }

        /// <summary>
        /// Client constructor
        /// </summary>
        public DigitalNewzealandClient(string apiKey)
        {
            Configuration.ApiKey = apiKey;
        }
    }
}